#--------------------- Database connection ---------------------
spring:
    flyway:
        locations: classpath:db/migration, classpath:db/migration/default, classpath:db/migration/script
        create-schemas: true
        schemas: dashboard
        table: analytics_dashboard_db_flyway_version
        baseline-on-migrate: true
        baseline-version: 0
    jpa:
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                default_schema: dashboard

    datasource:
        url: jdbc:postgresql://localhost:5432/ai-analytics-dashboard
        username: sa
        password: localpg
        driver-class-name: org.postgresql.Driver
#--------------------- Logging Level ---------------------
logging:
    level:
        org.flywaydb: DEBUG
        org.hibernate.SQL: DEBUG
        org.springframework.boot.autoconfigure.flyway: DEBUG
